import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../widgets/header/Header";
import Footer from "../widgets/footer/Footer";
import ReactQueryProviders from "./providers/ReactQueryProviders";
import { UserProvider } from "./providers/UserProviders";
import { SocketProvider } from "./providers/SocketProvider";

const montserrat = Montserrat();

export const metadata: Metadata = {
  title: "Online Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <ReactQueryProviders>
          <UserProvider>
            <SocketProvider>
              <div className="layout">
                <Header />
                {children}
                <Footer />
              </div>
            </SocketProvider>
          </UserProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
