import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../widgets/header/Header";
import Footer from "../widgets/footer/Footer";
import Script from "next/script";
import ReactQueryProviders from "./providers/ReactQueryProviders";

const montserrat = Montserrat();

export const metadata: Metadata = {
  title: "Online Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <div className="layout">
          <ReactQueryProviders>
            <Header />
            {children}
            <Footer />
          </ReactQueryProviders>
        </div>
      </body>
    </html>
  );
}
